version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Dockerhub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            date=$(date "+%Y-%m-%d")
            git_ref=$(git --no-pager log -1 --pretty=%h)
            docker build -t navikt/pt-sak-consumer:latest -t navikt/pt-sak-consumer:${date}-${git_ref} .
            docker push navikt/pt-sak-consumer:latest
            docker push navikt/pt-sak-consumer:${date}-${git_ref}
