version: 2.1
orbs:
  nais: navikt/nais-deployment@2.0.0
executors:
  openjdk:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/app
jobs:
  build:
    executor: openjdk
    steps:
      - checkout
      - run: echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)-$CIRCLE_BUILD_NUM" > .version
      - persist_to_workspace:
          root: ~/app
          paths:
            - .version
      - nais/docker-build:
          registry: docker.pkg.github.com
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/ptsak-consumer
          tag: $(cat .version)
      - nais/docker-push:
          registry: docker.pkg.github.com
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/ptsak-consumer
          tag: $(cat .version)
  deploy:
    executor: nais/deployment-cli
    steps:
      - nais-deploy:
          environment: dev-fss
      - nais-deploy:
          environment: prod-fss
commands:
  nais-deploy:
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - nais/deploy-with-personal-token:
            repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            image: docker.pkg.github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/ptsak-consumer
            tag: $(cat ~/app/.version)
            nais-template: nais/<< parameters.environment >>.yml
            environment: << parameters.environment >>
            team: ptsak
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
