version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
     - run: 
          name: Define version for this build
          command: |
            version=$(echo $(date "+%Y-%m-%d")-$(git --no-pager log -1 --pretty=%h))
            echo 'export IMAGE_VERSION="$(version)"' >> $BASH_ENV
     - run:
          name: Build Docker container
          command: |
            docker build -t navikt/pt-sak-consumer:latest -t navikt/pt-sak-consmer:${IMAGE_VERSION} .
      - run:
          name: Push Docker container
          command: |
            docker push navikt/pt-sak-consumer:latest
            docker push navikt/pt-sak-consumer:${IMAGE_VERSION}
