name: Deploy to NAIS
on: push
jobs:
  checkout:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create Docker tag
        env:
          REPO: ${{ github.repository }}
          NAME: ptsak-consumer
        run: |
          cd $GITHUB_WORKSPACE
          export DOCKER_TAG="docker.pkg.github.com"/"$REPO"/"$NAME":"$(git rev-parse --short HEAD)"
      - name: Build Docker image
        run: "docker build -t $(cat $HOME/.tag) ."
      - name: Login to Github Package Registry
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com
      - name: Push Docker image
        run: "docker push $(cat .tag)"
      - name: deploy to dev-fss
        uses: navikt/deployment-cli@4a9fde2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-fss
          repository: ${{ github.repository }}
          team: your-team
          resource: nais.yaml
