name: Deploy to NAIS
on: push
jobs:
  checkout:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create Docker tag
        env:
          REPO: ${{ github.repository }}
          NAME: ptsak-consumer
        run: |
          cd $GITHUB_WORKSPACE
          export TAG=$(git rev-parse --short HEAD)
          echo "docker.pkg.github.com"/"$REPO"/"$NAME":"$TAG" > $HOME/.tag

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: "docker build -t $(cat .tag) ."

  docker-push:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Package Registry
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com
      - name: Push Docker image
        run: "docker push $(cat .tag)"
  deploy:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    steps:
      - name: Create env variable
        run: "export DOCKER_TAG=$(cat .tag)"
      - name: deploy to dev-fss
        uses: navikt/deployment-cli@4a9fde2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-fss
          repository: ${{ github.repository }}
          team: your-team
          resource: nais.yaml
