name: Deploy to NAIS
on: push
jobs:
  checkout:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create Docker tag
        env:
          REPO: ${{ github.repository }}
          NAME: ptsak-consumer
        run: |
          pwd
          ls
          cd $GITHUB_WORKSPACE
          pwd
          ls
          echo "docker.pkg.github.com"/"$REPO"/"$NAME":"$(git rev-parse --short HEAD)" > .docker_tag
          cp .docker_tag $HOME/.docker_tag
      - name: Build Docker image
        run: |
          pwd
          ls
          cat .docker_tag
          cat $HOME/.docker_tag
          docker build -t $DOCKER_TAG .
      - name: Login to Github Package Registry
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com
      - name: Push Docker image
        run: "docker push $DOCKER_TAG"
      - name: deploy to dev-fss
        uses: navikt/deployment-cli/action@4a9fde2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-fss
          repository: ${{ github.repository }}
          team: your-team
          resource: nais.yaml
